name: Publish to Maven Central
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 21 for deploy to Sonatype
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.4'
          distribution: 'zulu'
          java-package: 'jdk+fx'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name:  Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup GPG
        id: gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "Importing key ..."
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --import --import-options import-show
          echo "Getting key id ..."
          key_id="$(echo "${GPG_PRIVATE_KEY}" | gpg --batch --show-keys --with-colons | awk -F: '$1 == "sec" { print $5 }')"
          echo "::set-output name=key_id::${key_id}"
      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_signing.gnupg.keyName: ${{ steps.gpg.outputs.key_id }}
          ORG_GRADLE_PROJECT_signing.gnupg.passphrase: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew build
      - name: Publish to Maven Central via Sonatype
        env:
            ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
            ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        run: ./gradlew uploadArchives
