name: Publish to Maven Central
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 21 for deploy to Sonatype
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.4'
          distribution: 'zulu'
          java-package: 'jdk+fx'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name:  Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build -Psonatype_user=${{ secrets.SONATYPE_USERNAME }} -Psonatype_password=${{ secrets.SONATYPE_PASSWORD }} -Psigning.password=${{ secrets.GPG_PASSPHRASE }} -Psigning.key=${{ secrets.GPG_PRIVATE_KEY }}
      - name: Publish to Maven Central via Sonatype
        run: ./gradlew uploadArchives
